apiVersion: v1
kind: Pod
metadata:
  name: error-test
  labels:
    name: errors
    type: all
spec:
  containers:
  # - name: comeon-matcha    this will leads to imageBackPullOff because the image is not exists
  #   image: comeon-matcha
  - name: almalinux
    image: almalinux:9  #this will give crashLoopBackOff because there is nothing to start the container
  