apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkinsUrl: "http://jenkins.krishna.com/build/job/2"
    imageRegistry: "https://hub.docker.com"
spec:
  containers:
  - name: annotations
    image: nginx
    