apiVersion: v1
kind: Service
metadata:
  name: np-service-demo
spec:
  type: NodePort
  selector:
    environment: development
    project: roboshop
    purpose: demo
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80