apiVersion: v1
kind: Pod
metadata:
  name: pod-lb-deme
  labels:
    environment: development
    project: roboshop
    purpose: loadbalancer-service
spec:
  containers:
  - name: pod-lb-demo
    image: nginx