apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  # these are rplica set labels
  labels:
    environment: development
    project: roboshop
spec:
  replicas: 5
  selector:
  # these labels are used to select pods
    matchLabels:
      environment: development
      project: roboshop
  #pod definition
  template:
    metadata:
      labels:
        environment: development
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
      
  